load("@com_nvidia_isaac//engine/build:isaac.bzl", "isaac_cc_library")

isaac_cc_library(
  name = "kaya_kinematics",
  srcs = [
    "kinematics.cpp"
  ],
  hdrs = [
    "kinematics.hpp"
  ],
  visibility = ["//visibility:public"],
  deps = [
    "@com_nvidia_isaac//engine/core/math",
  ]
)