load("@com_nvidia_isaac//engine/build:isaac.bzl", "isaac_cc_library")

isaac_cc_library(
    name = "kaya_kinematics",
    srcs = [
        "Kinematics.cpp"
    ],
    hdrs = [
        "Kinematics.hpp"
    ],
    visibility = ["//visibility:public"],
    deps = [
      "@com_nvidia_isaac//engine/core/math",
    ]
)